### ISSUE TITLE
external http signing template not working for private transactions

### ISSUE THREAD

**Issue by ethdev279** [jpmorganchase/quorum.js#16]
I tried deploying SimpleStorage contract on kaliedo quorum nodes(via node's json RPC address) with example you provided. I modified things that needed to modify. when I run this on node.js I ended up getting this error.
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:219:9)
    at base64toHex (C:\Users\ethdev\Desktop\qjs-dapp\lib\rawTransactionManager.js:18:19)
    at C:\Users\ethdev\Desktop\qjs-dapp\lib\rawTransactionManager.js:29:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
I thought it is the problem with buffer types in ```rawransactionManager.js``` module. or it is the problem with my setup?.  please let me know how to fix this.  quick response form u r end is highly appreciable 
@fixanoid

**Comment by fixanoid** [comment]
@ethdev279 this generally means that theres an error on the storeraw side. Are you connecting to the the correct Tessera node?

**Comment by ethdev279** [comment]
Yeah. I'm trying to connect quorum node from kaliedo platform

**Comment by fixanoid** [comment]
@ethdev279 please reopen if there is still an issue. Thanks.
