### ISSUE TITLE
Ability to send signed private transactions

### ISSUE THREAD

**Issue by dvgoyeneche** [jpmorganchase/quorum.js#21]
¿Is there any example (script) of how to sign a transaction (with the private key of the sender) and after make it privateFor some nodes?

**Comment by prd-fox** [comment]
There are a few examples in this project at https://github.com/jpmorganchase/quorum.js/tree/master/7nodes-test

If you have questions or issues running them, let me know.

**Comment by prd-fox** [comment]
Closing this as I consider the question answered. If it is not, please re-open. For new questions, please create a new issue.
