### ISSUE TITLE
[moved] from field is encrypted? 

### ISSUE THREAD

**Issue by prd-fox** [jpmorganchase/quorum.js#24]
>Hi there,
We are sending private transactions and we detect that the "from" is different from the account we are sending the transactions
Any idea?

Moves issue from https://github.com/jpmorganchase/tessera/issues/903 to correct repo

**Comment by prd-fox** [comment]
What version of `ethereumjs-tx` and `web3` are you using?
You might find that newer versions have added extra options and you will need to provide them when signing the tx. For example, can you try `var tx = new Tx(rawTx, { chain: 'mainnet', hardfork: 'homestead' });` instead of `var tx = new Tx(rawTx);`.

**Comment by dvgoyeneche** [comment]
Web3 1.0.0-beta36   (we extend web3 using quorum-js)
ethereumjs-tx 2.1.1

**Comment by prd-fox** [comment]
It looks like the docs site wasn't updated to reflect this change. The suggestion I posted above should be the course of action for the version `2.1.1` of `ethereumjs-tx`.
Can you try and let me know?

**Comment by dvgoyeneche** [comment]
We have tried:

const Web3 = require("web3");
const web3 = new Web3(new Web3.providers.HttpProvider("http://192.168.2.104:22000"));
const quorumjs = require("quorum-js");
quorumjs.extend(web3);
var Tx = require('ethereumjs-tx').Transaction;

var key = "ApDgrsugpOJpNMuYwrF9C808aH04+ddL9wgDfSqIzo4FAb4F+D1JqDzD1xtbf8KWZz7+zUnxWeO7HD+kV4fIDg=="
var data = "0x" + Buffer.from(key, 'base64').toString('hex');

var privateKey = new Buffer('03110633f4f6cbc1093b0b0efd78df97a07238f48108836696a9beb07259d35f', 'hex')
var rawTx = {
    gasPrice: '0x0',
    gasLimit: '0x842710',
    to: '0x107b4f9af0345bdd56a49d48f9e4d5e63c96af85',
    value: '0x00',
    data: data
}
var tx = new Tx(rawTx, { chain: 'mainnet', hardfork: 'homestead' });
tx.sign(privateKey);
var serializedTx = tx.serialize();
web3.eth.sendRawPrivateTransaction('0x' + serializedTx.toString('hex'), {
    privateFor: [ "AJlaQh6gnlfa+5FkZBibkSpTL7BneHQxe1MtG6qFe2k=", "DK4ek67pqbe1yhcUNr+mBrUl2EhAS22vgNiy7jXYiFw=", "86dxh3B9soDQARtx3YRRnkf4hE15li88BYCFSlTfFCU="]
}, function (err, hash) {
    if (!err) {
        console.log(hash);
        web3.eth.getTransactionReceipt(hash).then(console.log)
    } else {
        console.log("=============err");
        console.log(err);
    }
});


We get "Transaction is not private" error

**Comment by prd-fox** [comment]
Ah, missed the fact you are calling the Quorum API manually.

The `quorum.js` was to do it is shown here: https://github.com/jpmorganchase/quorum.js/blob/master/7nodes-test/deployContractViaHttp-externalSigningTemplate.js.

If you insist on calling the API yourself, then you need to update the `V` value of the signed transaction to be `10` higher than its given value (i.e. `27` becomes `37` and `28` becomes `38`).

**Comment by dvgoyeneche** [comment]
Thanks Peter, we will try, ¿How can we change the v value?

**Comment by prd-fox** [comment]
No worries, it's been a while since I've looked at this myself :)

A very quick and dirty solution:
```
if (tx.v.toString("hex") === "1b") {
    tx.v = Buffer("25", "hex");
} else {
    tx.v = Buffer("26", "hex")
}
```

**Comment by fixanoid** [comment]
You can also see how we set it here: https://github.com/jpmorganchase/quorum.js/blob/master/lib/rawTransactionManager.js#L67
