### ISSUE TITLE
How secure is this?

### ISSUE THREAD

**Issue by sssubik** [jpmorganchase/quorum.js#31]
Hey I was running through the example to deployContractViaHttp-externalSigningTemplate.js?
Is this code secure to run on an actual production server?

```
const signAcct = web3.eth.accounts.decrypt(
  {
    address: accAddress,
    crypto: {
      cipher: "aes-128-ctr",
      ciphertext:
        "4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377",
      cipherparams: {iv: "a8932af2a3c0225ee8e872bc0e462c11"},
      kdf: "scrypt",
      kdfparams: {
        dklen: 32,
        n: 262144,
        p: 1,
        r: 8,
        salt: "8ca49552b3e92f79c51f2cd3d38dfc723412c212e702bd337a3724e8937aff0f"
      },
      mac: "6d1354fef5aa0418389b1a5d1f5ee0050d7273292a1171c51fd02f9ecff55264"
    },
    id: "a65d1ac3-db7e-445d-a1cc-b6c5eeaa05e0",
    version: 3
  },
  ""
);
 
```
I wanted a safe way to send a transaction on the production server where the GETH node is running.

**Comment by x5engine** [comment]
This is not related to quorum.js, this is a normal decrypt of the account you are going to use!

Read more about here:
https://web3js.readthedocs.io/en/v1.2.7/web3-eth-accounts.html#decrypt

so this is the same as using a private key or something else.

**Comment by fixanoid** [comment]
@sssubik this is server side code, so this is as safe as you make your perimeter. That said, this is how its commonly done by other applications as well.
