### ISSUE TITLE
How to use with Azure Blockchain Service?

### ISSUE THREAD

**Issue by x5engine** [jpmorganchase/quorum.js#33]
Hello Guys, you did some great work and I love it.

I have an Azure Blockchain Service: which is running [Quorum 2.2.3](https://docs.microsoft.com/en-us/azure/blockchain/service/ledger-versions)

So it has all the latest updates, I am running two nodes in it (and another one for validation)

I cannot find or access **Tessera** to encrypt and send a **private transaction**, I don't know where or how to get the privateUrl or API... 

```
const rtmViaAPI = quorumjs.RawTransactionManager(web3, {
        privateUrl: "https://x5engine.blockchain.azure.com:3200"//can't find the right endpoint sadly
      })
```
```
      const rawTransaction = {
        nonce: `0x${nonce.toString(16)}`,
        from: "0x3f833ebc25100a391C61a2D40A3f16a08c98FB0c",
        to: "0xc5bAd721fb0CDE3FBa9B952BFA8B0B703Cc822C6",
        value: `0x${(0).toString(16)}`,
        gasLimit: `0x${(4300000).toString(16)}`,
        gasPrice: `0x${(0).toString(16)}`,
        data: encoded,
        privateFor: ["llGj6iwxark5ULgJ7vh1x6mmrI8KeDbFpd28xCg1YFk="],
        // privateFrom: "nOzQJIDGKR3Qa7yBwfp4TDnHawdxJU61RtXzuy1O4lg=",
        isPrivate: true
      };
      //this is how it should be sent as private
      rtmViaAPI.sendRawTransaction(rawTransaction)
       .then(function (o, e) {
             console.log("Sending private txn using newer API");
             console.log(o, e);
        });
```
I have access to the nodes and can send and ready transaction perfectly.

You can see my repo and live app [here](https://github.com/x5engine/dapp-Private-Encrypted-Transaction) and also check the logs.

Sending on node 1 as private and getting the transaction from node 2 and normally should be encrypted on it and can't be read.

So either it is enabled and I can't find where the privateUrl or endpoint is, or it is not enabled and I have to deploy the 7nodes examples which have Quorum nodes and I can access the server to enable or change the settings ( but I don't prefer this method because it will take more of my credit and I need to use Azure Blockchain Service) 

Thank you

**Comment by x5engine** [comment]
Hey @fixanoid can you take a look into this? please.

thanks

**Comment by fixanoid** [comment]
@x5engine as far as I know, Azure offering does not expose internal private transaction manager when using Managed Blockchain Service which means that it is not going to be possible to send private txns the raw way. You may still use the account generated on the node to send private txns tho.

**Comment by x5engine** [comment]
okay, @fixanoid so how can I use the account generated on the node to send private txns tho??
any code examples? I tried to do that failed but it still not private.
Should I set up a 7nodes too?

**Comment by fixanoid** [comment]
@x5engine you would use web3.js without Quorum in that case. See https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/private-contract.js#L11

**Comment by x5engine** [comment]
nice @fixanoid that's what I have used but it not private,

https://github.com/x5engine/dapp-Private-Encrypted-Transaction/blob/master/src/App.js#L146

I have two nodes on the ABS, one should be able to access it and the node2 I getTransaction by hash to see the input data and it should be encrypted for it but it seems it is not...

**Comment by x5engine** [comment]
You can see the app live here using what you suggested 

https://azure-quorum-tessera.x5engine.com/

and check the console for all output :)


thank you so much

**Comment by x5engine** [comment]
@fixanoid any answer on this, please :)
