### ISSUE TITLE
TypeError: web3.extend is not a function

### ISSUE THREAD

**Issue by coolcode** [jpmorganchase/quorum.js#9]
The provided method **extend**  in web3js  1.0.0.beta38 does no longer exist since Jan 26, 2019. [According to its official medium](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b#8746) 
So the function **quorumjs.extend(web3)** doesn't work --

TypeError: web3.extend is not a function 

```
const web3 = new Web3("http://xxxx");
const quorumjs = require("quorum-js");
quorumjs.extend(web3);
```

**Comment by fixanoid** [comment]
We are aware of the issue but the lack of documentation on the module development and overall instability of web3 at the moment kinda puts us in a weird position.

quorum.js package is locked to the web3 1.0.0-beta.36, and we will update it once web3 reaches production release with a correct implementation of the extension module to support Quorum native APIs.
